name: alpacago/ci

on:
  pull_request:
    branches:
      - main
    paths-ignore:
      - '**.md'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    name: CI/CD Build
    strategy:
      matrix:
        go: [ '1.21.x',]
        os: [ ubuntu-latest ]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout 🛎
        uses: actions/checkout@main

      # Setup our base Go environment 🧬
      - name: Setup Go Environment
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go }}

      # Setup Tailscale VPN 📡
      - name: Tailscale
        uses: tailscale/github-action@v2
        with:
          oauth-client-id: ${{ secrets.TAILSCALE_OAUTH_CLIENT_ID }}
          oauth-secret: ${{ secrets.TAILSCALE_OAUTH_CLIENT_SECRET }}
          tags: ${{ secrets.TAILSCALE_OAUTH_CLIENT_ADVERTISED_TAGS }}
          version: '1.56.0'

      - name: Go Test
        run: go test ./... -race -coverprofile=coverage.txt -covermode=atomic